dist: trusty
os: linux
language: minimal
image: docker:latest
services:
- docker
before_install:
- docker info
- docker pull coqpolyhedra/build-box
script:
- >-
  docker run -v $PWD:/home/ci/coqdev coqpolyhedra/build-box
  sh -c 'cd coqdev && find . && opam config exec -- make'
