# -*- Makefile -*-

# --------------------------------------------------------------------
.PHONY: default build push

# --------------------------------------------------------------------
build: build

build:
	docker build -t coqpolyhedra/build-box:latest .

push:
	docker push coqpolyhedra/build-box
